## MovieLeans 1M 数据集

In [1]:
import pandas as pd
import pylab

In [2]:
unames =['user_id','gender','age','occupation','zip']
print(unames)

['user_id', 'gender', 'age', 'occupation', 'zip']

In [4]:
users = pd.read_table('movielens/users.dat',sep='::',header=None,names=unames)

F:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  if __name__ == '__main__':

In [32]:
ranmes =['user_id','movie_id','rating','timestamp']

In [33]:
ratings = pd.read_table('movielens/ratings.dat',sep='::',header=None,names=ranmes)

F:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  if __name__ == '__main__':

In [9]:
mnames =['movie_id','title','genres']

In [30]:
movies = pd.read_table('movielens/movies.dat',sep='::',header=None,names=mnames)

F:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  if __name__ == '__main__':

In [13]:
users[:5]

   user_id gender  age  occupation    zip
0        1      F    1          10  48067
1        2      M   56          16  70072
2        3      M   25          15  55117
3        4      M   45           7  02460
4        5      M   25          20  55455

In [34]:
ratings[:5]

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [19]:
movies[:5]

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

## 合并数据
- 与表之间要有相关联字段

In [39]:
data = pd.merge(pd.merge(ratings,users),movies)

In [41]:
type(data)

pandas.core.frame.DataFrame

In [45]:
data.ix[0]

user_id                                            1
movie_id                                        1193
rating                                             5
timestamp                                  978300760
gender                                             F
age                                                1
occupation                                        10
zip                                            48067
title         One Flew Over the Cuckoo's Nest (1975)
genres                                         Drama
Name: 0, dtype: object

In [63]:
mean_ratings = data.pivot_table('rating','title',columns='gender',aggfunc='mean')
print(mean_ratings)

gender                                                 F         M
title
$1,000,000 Duck (1971)                          3.375000  2.761905
'Night Mother (1986)                            3.388889  3.352941
'Til There Was You (1997)                       2.675676  2.733333
'burbs, The (1989)                              2.793478  2.962085
...And Justice for All (1979)                   3.828571  3.689024
1-900 (1994)                                    2.000000  3.000000
10 Things I Hate About You (1999)               3.646552  3.311966
101 Dalmatians (1961)                           3.791444  3.500000
101 Dalmatians (1996)                           3.240000  2.911215
12 Angry Men (1957)                             4.184397  4.328421
13th Warrior, The (1999)                        3.112000  3.168000
187 (1997)                                      2.428571  2.791667
2 Days in the Valley (1996)                     3.488889  3.244813
20 Dates (1998)                                 2.620690  2.918182
20,000 Leagues Under the Sea (1954)             3.670103  3.709205
200 Cigarettes (1999)                           3.169014  2.700000
2001: A Space Odyssey (1968)                    3.825581  4.129738
2010 (1984)                                     3.446809  3.413712
24 7: Twenty Four Seven (1997)                  5.000000  3.750000
24-hour Woman (1998)                            2.000000  1.600000
28 Days (2000)                                  3.209424  2.977707
3 Ninjas: High Noon On Mega Mountain (1998)     1.400000  1.351351
3 Strikes (2000)                                     NaN  2.750000
301, 302 (1995)                                 3.000000  2.857143
39 Steps, The (1935)                            3.965517  4.107692
400 Blows, The (Les Quatre cents coups) (1959)  4.489362  4.264286
42 Up (1998)                                    3.966667  4.362069
52 Pick-Up (1986)                               3.304348  3.299145
54 (1998)                                       2.701754  2.782178
7th Voyage of Sinbad, The (1958)                3.409091  3.658879
...                                                  ...       ...
Wrongfully Accused (1998)                       2.666667  2.540541
Wyatt Earp (1994)                               3.147059  3.283898
X-Files: Fight the Future, The (1998)           3.489474  3.493797
X-Men (2000)                                    3.682310  3.851702
X: The Unknown (1956)                           2.250000  3.125000
Xiu Xiu: The Sent-Down Girl (Tian yu) (1998)    3.821429  3.536585
Yankee Zulu (1994)                              3.000000  3.000000
Yards, The (1999)                               2.687500  3.360656
Year My Voice Broke, The (1987)                 4.000000  3.705882
Year of Living Dangerously (1982)               3.951220  3.869403
Year of the Horse (1997)                             NaN  3.250000
Yellow Submarine (1968)                         3.714286  3.689286
Yojimbo (1961)                                  4.423077  4.402116
You Can't Take It With You (1938)               4.192308  3.921569
You So Crazy (1994)                             3.666667  2.300000
You've Got Mail (1998)                          3.542424  3.275591
Young Doctors in Love (1982)                    1.923077  2.742424
Young Frankenstein (1974)                       4.289963  4.239177
Young Guns (1988)                               3.371795  3.425620
Young Guns II (1990)                            2.934783  2.904025
Young Poisoner's Handbook, The (1995)           4.000000  3.532258
Young Sherlock Holmes (1985)                    3.514706  3.363344
Young and Innocent (1937)                       2.500000  3.500000
Your Friends and Neighbors (1998)               2.888889  3.536585
Zachariah (1971)                                     NaN  3.500000
Zed & Two Noughts, A (1985)                     3.500000  3.380952
Zero Effect (1998)                              3.864407  3.723140
Zero Kelvin (Kj鎟lighetens kj鴗ere) (1995)             NaN  3.500000
Zeus and Roxanne (1997)                         2.777778  2.357143
eXistenZ (1999)                                 3.098592  3.289086

[3706 rows x 2 columns]

In [65]:
print(help(data.pivot_table))

Help on method pivot_table in module pandas.tools.pivot:

pivot_table(values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All') method of pandas.core.frame.DataFrame instance
    Create a spreadsheet-style pivot table as a DataFrame. The levels in the
    pivot table will be stored in MultiIndex objects (hierarchical indexes) on
    the index and columns of the result DataFrame

    Parameters
    ----------
    data : DataFrame
    values : column to aggregate, optional
    index : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The list
        can contain any of the other types (except list).
        Keys to group by on the pivot table index.  If an array is passed, it
        is being used as the same manner as column values.
    columns : column, Grouper, array, or list of the previous
        If an array is passed, it must be the same length as the data. The list
        can contain any of the other types (except list).
        Keys to group by on the pivot table column.  If an array is passed, it
        is being used as the same manner as column values.
    aggfunc : function or list of functions, default numpy.mean
        If list of functions passed, the resulting pivot table will have
        hierarchical columns whose top level are the function names (inferred
        from the function objects themselves)
    fill_value : scalar, default None
        Value to replace missing values with
    margins : boolean, default False
        Add all row / columns (e.g. for subtotal / grand totals)
    dropna : boolean, default True
        Do not include columns whose entries are all NaN
    margins_name : string, default 'All'
        Name of the row / column that will contain the totals
        when margins is True.

    Examples
    --------
    >>> df
       A   B   C      D
    0  foo one small  1
    1  foo one large  2
    2  foo one large  2
    3  foo two small  3
    4  foo two small  3
    5  bar one large  4
    6  bar one small  5
    7  bar two small  6
    8  bar two large  7

    >>> table = pivot_table(df, values='D', index=['A', 'B'],
    ...                     columns=['C'], aggfunc=np.sum)
    >>> table
              small  large
    foo  one  1      4
         two  6      NaN
    bar  one  5      4
         two  6      7

    Returns
    -------
    table : DataFrame

None

- 去掉评分数据不够250条的电影

In [68]:
ratings_by_title = data.groupby('title').size()

In [69]:
ratings_by_title[:5]

title
$1,000,000 Duck (1971)            37
'Night Mother (1986)              70
'Til There Was You (1997)         52
'burbs, The (1989)               303
...And Justice for All (1979)    199
dtype: int64

In [70]:
actives_titles = ratings_by_title.index[ratings_by_title>=250]

In [71]:
actives_titles[:5]

Index([''burbs, The (1989)', '10 Things I Hate About You (1999)',
       '101 Dalmatians (1961)', '101 Dalmatians (1996)',
       '12 Angry Men (1957)'],
      dtype='object', name='title')

In [72]:
mean_ratings = mean_ratings.ix[actives_titles]

In [73]:
mean_ratings

gender                                                     F         M
title
'burbs, The (1989)                                  2.793478  2.962085
10 Things I Hate About You (1999)                   3.646552  3.311966
101 Dalmatians (1961)                               3.791444  3.500000
101 Dalmatians (1996)                               3.240000  2.911215
12 Angry Men (1957)                                 4.184397  4.328421
13th Warrior, The (1999)                            3.112000  3.168000
2 Days in the Valley (1996)                         3.488889  3.244813
20,000 Leagues Under the Sea (1954)                 3.670103  3.709205
2001: A Space Odyssey (1968)                        3.825581  4.129738
2010 (1984)                                         3.446809  3.413712
28 Days (2000)                                      3.209424  2.977707
39 Steps, The (1935)                                3.965517  4.107692
54 (1998)                                           2.701754  2.782178
7th Voyage of Sinbad, The (1958)                    3.409091  3.658879
8MM (1999)                                          2.906250  2.850962
About Last Night... (1986)                          3.188679  3.140909
Absent Minded Professor, The (1961)                 3.469388  3.446809
Absolute Power (1997)                               3.469136  3.327759
Abyss, The (1989)                                   3.659236  3.689507
Ace Ventura: Pet Detective (1994)                   3.000000  3.197917
Ace Ventura: When Nature Calls (1995)               2.269663  2.543333
Addams Family Values (1993)                         3.000000  2.878531
Addams Family, The (1991)                           3.186170  3.163498
Adventures in Babysitting (1987)                    3.455782  3.208122
Adventures of Buckaroo Bonzai Across the 8th Di...  3.308511  3.402321
Adventures of Priscilla, Queen of the Desert, T...  3.989071  3.688811
Adventures of Robin Hood, The (1938)                4.166667  3.918367
African Queen, The (1951)                           4.324232  4.223822
Age of Innocence, The (1993)                        3.827068  3.339506
Agnes of God (1985)                                 3.534884  3.244898
...                                                      ...       ...
White Men Can't Jump (1992)                         3.028777  3.231061
Who Framed Roger Rabbit? (1988)                     3.569378  3.713251
Who's Afraid of Virginia Woolf? (1966)              4.029703  4.096939
Whole Nine Yards, The (2000)                        3.296552  3.404814
Wild Bunch, The (1969)                              3.636364  4.128099
Wild Things (1998)                                  3.392000  3.459082
Wild Wild West (1999)                               2.275449  2.131973
William Shakespeare's Romeo and Juliet (1996)       3.532609  3.318644
Willow (1988)                                       3.658683  3.453543
Willy Wonka and the Chocolate Factory (1971)        4.063953  3.789474
Witness (1985)                                      4.115854  3.941504
Wizard of Oz, The (1939)                            4.355030  4.203138
Wolf (1994)                                         3.074074  2.899083
Women on the Verge of a Nervous Breakdown (1988)    3.934307  3.865741
Wonder Boys (2000)                                  4.043796  3.913649
Working Girl (1988)                                 3.606742  3.312500
World Is Not Enough, The (1999)                     3.337500  3.388889
Wrong Trousers, The (1993)                          4.588235  4.478261
Wyatt Earp (1994)                                   3.147059  3.283898
X-Files: Fight the Future, The (1998)               3.489474  3.493797
X-Men (2000)                                        3.682310  3.851702
Year of Living Dangerously (1982)                   3.951220  3.869403
Yellow Submarine (1968)                             3.714286  3.689286
You've Got Mail (1998)                              3.542424  3.275591
Young Frankenstein (1974)                           4.289963  4.239177
Young Guns (1988)                                   3.371795  3.425620
Young Guns II (1990)                                2.934783  2.904025
Young Sherlock Holmes (1985)                        3.514706  3.363344
Zero Effect (1998)                                  3.864407  3.723140
eXistenZ (1999)                                     3.098592  3.289086

[1216 rows x 2 columns]

- 女性最喜欢的电影

In [74]:
top_female_ratings = mean_ratings.sort_index(by='F',ascending=False)

F:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  if __name__ == '__main__':

In [75]:
top_female_ratings[:10]

gender                                                     F         M
title
Close Shave, A (1995)                               4.644444  4.473795
Wrong Trousers, The (1993)                          4.588235  4.478261
Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)       4.572650  4.464589
Wallace & Gromit: The Best of Aardman Animation...  4.563107  4.385075
Schindler's List (1993)                             4.562602  4.491415
Shawshank Redemption, The (1994)                    4.539075  4.560625
Grand Day Out, A (1992)                             4.537879  4.293255
To Kill a Mockingbird (1962)                        4.536667  4.372611
Creature Comforts (1990)                            4.513889  4.272277
Usual Suspects, The (1995)                          4.513317  4.518248

- 计算评分分歧

In [78]:
mean_ratings['diff'] = mean_ratings['M']-mean_ratings['F']

In [79]:
mean_ratings

gender,F,M,diff
title,,,
"'burbs, The (1989)",2.793478,2.962085,0.168607
10 Things I Hate About You (1999),3.646552,3.311966,-0.334586
101 Dalmatians (1961),3.791444,3.500000,-0.291444
101 Dalmatians (1996),3.240000,2.911215,-0.328785
12 Angry Men (1957),4.184397,4.328421,0.144024
"13th Warrior, The (1999)",3.112000,3.168000,0.056000
2 Days in the Valley (1996),3.488889,3.244813,-0.244076
"20,000 Leagues Under the Sea (1954)",3.670103,3.709205,0.039102
2001: A Space Odyssey (1968),3.825581,4.129738,0.304156
2010 (1984),3.446809,3.413712,-0.033097
28 Days (2000),3.209424,2.977707,-0.231717
"39 Steps, The (1935)",3.965517,4.107692,0.142175
54 (1998),2.701754,2.782178,0.080424
"7th Voyage of Sinbad, The (1958)",3.409091,3.658879,0.249788
8MM (1999),2.906250,2.850962,-0.055288
About Last Night... (1986),3.188679,3.140909,-0.047770
"Absent Minded Professor, The (1961)",3.469388,3.446809,-0.022579
Absolute Power (1997),3.469136,3.327759,-0.141377
"Abyss, The (1989)",3.659236,3.689507,0.030272
Ace Ventura: Pet Detective (1994),3.000000,3.197917,0.197917
Ace Ventura: When Nature Calls (1995),2.269663,2.543333,0.273670
Addams Family Values (1993),3.000000,2.878531,-0.121469
"Addams Family, The (1991)",3.186170,3.163498,-0.022672
Adventures in Babysitting (1987),3.455782,3.208122,-0.247660
"Adventures of Buckaroo Bonzai Across the 8th Dimension, The (1984)",3.308511,3.402321,0.093810
"Adventures of Priscilla, Queen of the Desert, The (1994)",3.989071,3.688811,-0.300260
"Adventures of Robin Hood, The (1938)",4.166667,3.918367,-0.248299
"African Queen, The (1951)",4.324232,4.223822,-0.100410
"Age of Innocence, The (1993)",3.827068,3.339506,-0.487561
Agnes of God (1985),3.534884,3.244898,-0.289986
...,...,...,...
White Men Can't Jump (1992),3.028777,3.231061,0.202284
Who Framed Roger Rabbit? (1988),3.569378,3.713251,0.143873
Who's Afraid of Virginia Woolf? (1966),4.029703,4.096939,0.067236
"Whole Nine Yards, The (2000)",3.296552,3.404814,0.108262
"Wild Bunch, The (1969)",3.636364,4.128099,0.491736
Wild Things (1998),3.392000,3.459082,0.067082
Wild Wild West (1999),2.275449,2.131973,-0.143476
William Shakespeare's Romeo and Juliet (1996),3.532609,3.318644,-0.213965
Willow (1988),3.658683,3.453543,-0.205139
Willy Wonka and the Chocolate Factory (1971),4.063953,3.789474,-0.274480
Witness (1985),4.115854,3.941504,-0.174349
"Wizard of Oz, The (1939)",4.355030,4.203138,-0.151892
Wolf (1994),3.074074,2.899083,-0.174992
Women on the Verge of a Nervous Breakdown (1988),3.934307,3.865741,-0.068566
Wonder Boys (2000),4.043796,3.913649,-0.130147
Working Girl (1988),3.606742,3.312500,-0.294242
"World Is Not Enough, The (1999)",3.337500,3.388889,0.051389
"Wrong Trousers, The (1993)",4.588235,4.478261,-0.109974
Wyatt Earp (1994),3.147059,3.283898,0.136839
"X-Files: Fight the Future, The (1998)",3.489474,3.493797,0.004323
X-Men (2000),3.682310,3.851702,0.169391
Year of Living Dangerously (1982),3.951220,3.869403,-0.081817
Yellow Submarine (1968),3.714286,3.689286,-0.025000
You've Got Mail (1998),3.542424,3.275591,-0.266834
Young Frankenstein (1974),4.289963,4.239177,-0.050785
Young Guns (1988),3.371795,3.425620,0.053825
Young Guns II (1990),2.934783,2.904025,-0.030758
Young Sherlock Holmes (1985),3.514706,3.363344,-0.151362
Zero Effect (1998),3.864407,3.723140,-0.141266
eXistenZ (1999),3.098592,3.289086,0.190494

In [81]:
sorted_by_diff = mean_ratings.sort_index(by='diff')

F:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  if __name__ == '__main__':

In [82]:
sorted_by_diff[:10]

gender                                        F         M      diff
title
Dirty Dancing (1987)                   3.790378  2.959596 -0.830782
Jumpin' Jack Flash (1986)              3.254717  2.578358 -0.676359
Grease (1978)                          3.975265  3.367041 -0.608224
Little Women (1994)                    3.870588  3.321739 -0.548849
Steel Magnolias (1989)                 3.901734  3.365957 -0.535777
Anastasia (1997)                       3.800000  3.281609 -0.518391
Rocky Horror Picture Show, The (1975)  3.673016  3.160131 -0.512885
Color Purple, The (1985)               4.158192  3.659341 -0.498851
Age of Innocence, The (1993)           3.827068  3.339506 -0.487561
Free Willy (1993)                      2.921348  2.438776 -0.482573

In [83]:
sorted_by_diff[::-1][:10] #男性更喜欢的电影

gender                                         F         M      diff
title
Good, The Bad and The Ugly, The (1966)  3.494949  4.221300  0.726351
Kentucky Fried Movie, The (1977)        2.878788  3.555147  0.676359
Dumb & Dumber (1994)                    2.697987  3.336595  0.638608
Longest Day, The (1962)                 3.411765  4.031447  0.619682
Cable Guy, The (1996)                   2.250000  2.863787  0.613787
Evil Dead II (Dead By Dawn) (1987)      3.297297  3.909283  0.611985
Hidden, The (1987)                      3.137931  3.745098  0.607167
Rocky III (1982)                        2.361702  2.943503  0.581801
Caddyshack (1980)                       3.396135  3.969737  0.573602
For a Few Dollars More (1965)           3.409091  3.953795  0.544704

- 不考虑性别找出分歧最大的电影,可计算数据的方差和标准差

In [84]:
#标准差
rating_std_by_title = data.groupby('title')['rating'].std()

In [85]:
#过滤掉评论少于250的数据
rating_std_by_title = rating_std_by_title.ix[actives_titles]

In [86]:
#降序排列
rating_std_by_title.order(ascending=False)[:10]

F:\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: order is deprecated, use sort_values(...)
  from ipykernel import kernelapp as app

title
Dumb & Dumber (1994)                     1.321333
Blair Witch Project, The (1999)          1.316368
Natural Born Killers (1994)              1.307198
Tank Girl (1995)                         1.277695
Rocky Horror Picture Show, The (1975)    1.260177
Eyes Wide Shut (1999)                    1.259624
Evita (1996)                             1.253631
Billy Madison (1995)                     1.249970
Fear and Loathing in Las Vegas (1998)    1.246408
Bicentennial Man (1999)                  1.245533
Name: rating, dtype: float64